### ISSUE TITLE
Have there been any changes to ZZZ API endpoints?

### ISSUE THREAD

**Issue by Senul8** [sglkc/hoyolab-auto-daily#14]
Hello.
It was working until a few days ago, but now it shows 
{'data': None, 'message': '活动已结束 (-500012)', 'retcode': -500012} in the log and seems not to work with ZZZ.

Genshin, Honkai 3rd  and Honkai Star-rail are working fine.

Do you have any solutions?

**Comment by sglkc** [comment]
it has been fixed with #9 you have to update your fork
