### ISSUE TITLE
ZZZ "Too many requests"

### ISSUE THREAD

**Issue by Behem07h** [sglkc/hoyolab-auto-daily#15]
`Run node index.js
-- CHECKING IN FOR ACCOUNT 1 --

----- CHECKING IN FOR zzz -----
zzz Error undocumented, report to Issues page if this persists
zzz Headers {
  'access-control-allow-credentials': 'true',
  'access-control-allow-origin': 'https://act.hoyolab.com/',
  'access-control-expose-headers': 'Ab_experiment_info_v1, X-Rpc-Verify',
  'cache-control': 'no-cache',
  connection: 'keep-alive',
  'content-length': '56',
  'content-type': 'application/json',
  date: 'Tue, 22 Oct 2024 22:12:49 GMT',
  'set-cookie': 'ltuid_v2=my_ltuid_v2; Path=/; Domain=hoyolab.com; Max-Age=31536000; Secure',
  vary: 'Origin, Accept-Encoding',
  via: '1.1 1f85764c0bc1f70d16858df07753dfa8.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'i4r7mzQg33xFSXJH6U4nbuMj4BQa7jgRLcLy3QtIyRdjo21FcNmXng==',
  'x-amz-cf-pop': 'JFK52-P3',
  'x-cache': 'Miss from cloudfront',
  'x-powered-by': 'takumi',
  'x-trace-id': '4a9ad6a586d6527b:4a9ad6a586d6527b:0:1'
}
zzz Response { data: null, message: 'too many requests', retcode: -1 }
file:///home/runner/work/hoyolab-auto-daily/hoyolab-auto-daily/index.js:189
  throw new Error('Error(s) occured.')
        ^

Error: Error(s) occured.
    at file:///home/runner/work/hoyolab-auto-daily/hoyolab-auto-daily/index.js:189:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.0

Error: Process completed with exit code 1.`

(ltuid_v2 censored from traceback)

It has been running fine for the past week, then suddenly this error popped up. Manually rerunning the workflow resulted in a successful checkin

**Comment by sglkc** [comment]
Wait for next check-in and see if it still fails
